<?php return array (
  'captivename' => 'Aeroport del Prat Wi-Fi',
  'loginphp_file' => 'login/login.php',
  'db_name' => 'portalcautivo',
  'db_server' => '127.0.0.1',
  'db_tableauth' => 'login',
  'db_username' => 'root',
  'db_password' => 'Sintesis#123',
  'internal_int' => 'enp0s8',
  'internal_ip' => '10.222.0.1',
  'external_int' => 'enp0s3',
  'external_subnet' => '10.110.0.0/16',
  'external_gateway' => '10.110.0.1',
  'dnsforwarder1' => '208.67.222.123',
  'dnsforwarder2' => '208.67.220.123',
  'free_time' => '30min',
  'premium_time' => '4hours',
  'premium1_time' => '8hours',
  'admin_time' => '24hours',
  'admin_mail' => 'admin@admin.com',
  'domain' => 'aeropuerto.webredirect.org',  
  'payment_gateway' => 'https://sis-t.redsys.es:25443/',
);